- menu_name: "People"

- name: "IOL Board"
  url: "/contact/"
  title: "IOL Board"

- name: "Problem Committee"
  url: "/feed.xml"
  title: "Problem Committee"

- name: "Local Organizers"
  url: "/atom.xml"
  title: "Local Organizers"

- name: "Participants"
  url: "/atom.xml"
  title: "Participants"
