- menu_name: "People"

- name: "IOL Board"
  url: "/board/"
  title: "IOL Board"

- name: "Problem Committee"
  url: "/pc/"
  title: "Problem Committee"

- name: "Local Organizers"
  url: "/local_organizers/"
  title: "Local Organizers"

- name: "All Participants"
  url: "/participants/"
  title: "All Participants"